controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - fr_steering_joint
      - fl_steering_joint
      - rr_steering_joint
      - rl_steering_joint

joint_trajectory_controller:
  ros__parameters:
    joints:
      - fr_steering_joint
      - fl_steering_joint
      - rr_steering_joint
      - rl_steering_joint

    command_interfaces:
      - position

    state_interfaces:
      - position




      # - fr_steering_joint
      # - fl_steering_joint
      # - rr_steering_joint
      # - rl_steering_joint